name: Build Image
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: log into dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: log into github packages docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get short sha
        id: vars
        run: |
          sha=$(git rev-parse --short HEAD)
          echo ::set-output name=id::${sha}
      - name: docker build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: build/package/Dockerfile
          tags: |
            dictybase/go-grpc-http-generator-${{ steps.vars.outputs.id }}
            docker.pkg.github.com/dictybase/go-grpc-http-generator/go-grpc-http-generator-${{ steps.vars.outputs.id }}